### ISSUE TITLE
Compatibility with MyBib Citation Generator

### ISSUE THREAD

**Issue by JanAlbr-FhG** [sandrofigo/obsidian-pretty-bibtex#1]
Thank you for your work. This is rather a feature request than an issue.

The MyBib Citation Generator @ https://www.mybib.com/ is an Addon for Browsers to generate citations on websites. It is possible to choose a Biblatex format. The Addon does not allow for customizing the format any further.

As far as i tested this in combination with pretty-bibtex, the obsidian plugin needs line breaks for each object (such as title, year, ...) to function correctly. MyBib outputs no line breaks, it is a single string with the formatted data.

If those addons would be compatible, it would be a great boost in value for pretty-bibtex.

Thank you, kind regards

**Comment by sandrofigo** [comment]
This would be possible to add, but I would need exact information on the behavior of the export function of the addon, since the format of the single line does not specify any tags/labels to identify the content between each section. (separated by `,`)

Supporting all the available citation formats (e.g. Chicago Manual, Harvard, IEEE, ...) that are in use globally is not in the scope of pretty-bibtex.

I had a look at the addon and it is possible to export a BibTeX entry from a citation, by downloading all the entries in the BibTeX format. I see that this might be unintuitive, but it is a possible workaround.

The normal citation export done via the context menu of a citation might look like this:
```
Oh-Hyun Kwon, et al. “Spherical Layout and Rendering Methods for Immersive Graph Visualization.” 2015 IEEE Pacific Visualization Symposium (PacificVis), Apr. 2015, 10.1109/pacificvis.2015.7156357.
```

The BibTeX entry exported with the download feature of the addon might look like this and should work with pretty-bibtex:
```
@article{ohhyunkwon_2015_spherical,
  author = {Oh-Hyun Kwon,  and Muelder, Chris and Kyungwon Lee,  and Kwan-Liu Ma, },
  month = {04},
  title = {Spherical layout and rendering methods for immersive graph visualization},
  doi = {10.1109/pacificvis.2015.7156357},
  year = {2015},
  journal = {2015 IEEE Pacific Visualization Symposium (PacificVis)}
}
```

I would suggest contacting the creator of the addon and requesting a feature to have an easier method of exporting the selected or all citations in the BibTeX format.
